/**
 * Deze applicatie biedt gebruikers de mogelijkheid om een DNA sequentie (in FASTA formaat) in te laden
 * en hierin aanwezige ORFs (gedefineerd als een DNA sequentie dat in frame begint met ATG en eindigt met een stop codon)
 * te vinden,visualiseren en eventueel op te slaan in een MySQL database.
 * Vereist BioJava 4.2.7 en mysql-connector 6.0.6.
 *
 * Deze applicatie volgt in grote lijnen het ontwerp, om de code overzichtelijker te houden
 * zijn er per functionaliteit (package) wel meer classes en methodes toegevoegd.
 *
 * Ontwikkelaars: Glenn Hulscher, Tijs van Lieshout, Koen van der Heide en Milo van de Griend
 * Datum laatste versie: 03-04-2017
 *
 * Bekende bugs:
 * - ORFs worden in de database nog niet verbonden aan de DNA sequentie.
 * - Als de FASTA file meerdere sequenties bevat wordt alleen de eerste sequentie hier verwerkt.
 * - BLAST functionaliteit mist nog.
 *
 */
package com.groep11.orfvoorspeller.gui;

import com.groep11.orfvoorspeller.bestandinladen.BestandOpener;
import com.groep11.orfvoorspeller.bestandinladen.BestandKiezer;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import org.biojava.nbio.core.exceptions.CompoundNotFoundException;
import org.biojava.nbio.core.sequence.DNASequence;
import com.groep11.orfvoorspeller.bestandinladen.AminoVoorspeller;
import com.groep11.orfvoorspeller.bestandinladen.FASTASequentie;
import com.groep11.orfvoorspeller.bestandinladen.FASTASequentieHelper;
import com.groep11.orfvoorspeller.orfstonen.ORF;
import com.groep11.orfvoorspeller.orfstonen.ORFSearcher;
import com.groep11.orfvoorspeller.bestandinladen.OngeldigBestandException;
import com.groep11.orfvoorspeller.orfstonen.OngeldigeORFException;
import com.groep11.orfvoorspeller.dataopslag.OngelijkAantalKolommenException;
import com.groep11.orfvoorspeller.dataopslag.SpecifiekeDataOpslag;
import java.io.FileInputStream;
import java.io.InputStream;

/**
 * De GUI class met alle noodzakelijke GUI elementen, niet alle onderdelen zijn
 * al verbonden met de noodzakelijke logica, zo kan een sequentie nog niet
 * lokaal worden opgeslagen
 *
 * @author Koen
 */
public class GUI extends javax.swing.JFrame {

    //nog blast in apart tab?
    private FASTASequentie fastaSequentie;
    private ArrayList<ORF> gevondenORFs;
    private boolean dnaSaved = false;
    private SpecifiekeDataOpslag opslag;

    /**
     * Maak instantie van de GUI en disable de vind ORFs knop (deze wordt pas
     * enabled wanneer er werkelijk een sequentie is ingeladen).
     */
    public GUI() {
        initComponents();
        vindORFsButton.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openButton = new javax.swing.JButton();
        padTextField = new javax.swing.JTextField();
        seqScrollPane = new javax.swing.JScrollPane();
        dnaSequentieTextPane = new javax.swing.JTextPane();
        headerLabel = new javax.swing.JLabel();
        vindORFsButton = new javax.swing.JButton();
        dummyUpperScrollPane = new javax.swing.JScrollPane();
        dummyUpperPanel = new javax.swing.JPanel();
        aaSequentieTextPaneUpper = new javax.swing.JTextPane();
        dummyLowerScrollPane = new javax.swing.JScrollPane();
        dummyPanel1 = new javax.swing.JPanel();
        aaSequentieTextPaneLower = new javax.swing.JTextPane();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        browseMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        saveDnaMenuItem = new javax.swing.JMenuItem();
        saveOrfsMenuItem = new javax.swing.JMenuItem();
        saveBlastMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        exportDnaMenuItem = new javax.swing.JMenuItem();
        exportOrfsMenuItem = new javax.swing.JMenuItem();
        exportBlastMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AANSCHOUW DE ORF VOORSPELLER");

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        dnaSequentieTextPane.setEditable(false);
        dnaSequentieTextPane.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        seqScrollPane.setViewportView(dnaSequentieTextPane);

        headerLabel.setMaximumSize(new java.awt.Dimension(300, 30));
        headerLabel.setMinimumSize(new java.awt.Dimension(300, 30));
        headerLabel.setPreferredSize(new java.awt.Dimension(300, 30));

        vindORFsButton.setText("Find ORFs");
        vindORFsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vindORFsButtonActionPerformed(evt);
            }
        });

        dummyUpperScrollPane.setPreferredSize(new java.awt.Dimension(8, 22));

        dummyUpperPanel.setLayout(new java.awt.BorderLayout());

        aaSequentieTextPaneUpper.setEditable(false);
        aaSequentieTextPaneUpper.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        aaSequentieTextPaneUpper.setPreferredSize(null);
        dummyUpperPanel.add(aaSequentieTextPaneUpper, java.awt.BorderLayout.CENTER);

        dummyUpperScrollPane.setViewportView(dummyUpperPanel);

        dummyLowerScrollPane.setPreferredSize(new java.awt.Dimension(8, 22));

        dummyPanel1.setLayout(new java.awt.BorderLayout());

        aaSequentieTextPaneLower.setEditable(false);
        aaSequentieTextPaneLower.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        aaSequentieTextPaneLower.setPreferredSize(null);
        dummyPanel1.add(aaSequentieTextPaneLower, java.awt.BorderLayout.CENTER);

        dummyLowerScrollPane.setViewportView(dummyPanel1);

        jMenu1.setText("File");

        browseMenuItem.setText("Browse");
        browseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(browseMenuItem);

        jMenu4.setText("Save as File..");

        saveDnaMenuItem.setText("Full DNA Seq");
        jMenu4.add(saveDnaMenuItem);

        saveOrfsMenuItem.setText("ORFs");
        jMenu4.add(saveOrfsMenuItem);

        saveBlastMenuItem.setText("BLAST");
        jMenu4.add(saveBlastMenuItem);

        jMenu1.add(jMenu4);

        MenuBar.add(jMenu1);

        jMenu2.setText("Export to DB");

        exportDnaMenuItem.setText("Full DNA Seq");
        exportDnaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportDnaMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(exportDnaMenuItem);

        exportOrfsMenuItem.setText("ORFs");
        exportOrfsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportOrfsMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(exportOrfsMenuItem);

        exportBlastMenuItem.setText("BLAST");
        jMenu2.add(exportBlastMenuItem);

        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dummyUpperScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(seqScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(dummyLowerScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(padTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(vindORFsButton)
                        .addGap(190, 190, 190))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openButton)
                    .addComponent(padTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vindORFsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dummyUpperScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seqScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dummyLowerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Wanneer gebruiker klikt op "Open" wordt deze methode aangeroepen, de
     * tekst in het tekstfield linksboven wordt ingelezen om de FASTA file waar
     * dit naar wijst te laden. De FASTA data in de file wordt opgeslagen en
     * getoond in de GUI.
     *
     * @param evt gebruiker klikt knop.
     */
    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        try {
            String filePad;
            File fastaFile;
            LinkedHashMap<String, DNASequence> ingeladenSequentie = new LinkedHashMap<>();

            //noodzakelijk omdat de gebruiker ook direct filepad in kan typen ipv te browsen
            filePad = padTextField.getText();
            fastaFile = new File(filePad);

            ingeladenSequentie = BestandOpener.openDNABestand(fastaFile);

            fastaSequentie = FASTASequentieHelper.saveFASTASequentie(ingeladenSequentie);
            headerLabel.setText(fastaSequentie.getTitel());

            AminoVoorspeller aminos = new AminoVoorspeller(fastaSequentie);
            dnaSequentieTextPane.setText(fastaSequentie.getSequentieMetComplementair());
            aaSequentieTextPaneUpper.setText(aminos.getForwardAminoSequentiesAlsString());
            aaSequentieTextPaneLower.setText(aminos.getReverseAminoSequentiesAlsString());

//verbind de scroll bars van de afzonderlijke text panes aan elkaar zodat gebruiker maar in 1 pane hoeft te scrollen
            dummyLowerScrollPane.setHorizontalScrollBar(dummyUpperScrollPane.getHorizontalScrollBar());
            seqScrollPane.setHorizontalScrollBar(dummyLowerScrollPane.getHorizontalScrollBar());

            vindORFsButton.setEnabled(true);

        } catch (OngeldigBestandException ex) {
            errorPopup("Invalid/No file chosen");
        } catch (IOException ex) {
            errorPopup("Error while reading file");
        } catch (NullPointerException ex) {
            errorPopup("File is empty!");
        }
    }//GEN-LAST:event_openButtonActionPerformed
    /**
     * Methode aangeroepen wanneer gebruiker op File -> Browse klikt, roept de
     * bestand browser aan en zet het filepad in de textfield.
     *
     * @param evt gebruiker selecteert menu item.
     */
    private void browseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseMenuItemActionPerformed
        BestandKiezer browser = new BestandKiezer();
        try {
            padTextField.setText(browser.setInputBrowseBestandPad()); //zet de file locatie als text in de textfield
        } catch (OngeldigBestandException ex) {
            errorPopup("No file chosen..");
        }

    }//GEN-LAST:event_browseMenuItemActionPerformed
    /**
     * Aangeroepen wanneer gebruiker op Export to DB -> ORFs klikt. Checkt of er
     * al een DNA sequentie is opgeslagen, zo ja dan laat deze methode de
     * gevonden ORFs opslaan in de MySQL DB.
     *
     * @param evt gebruiker selecteert het item.
     */
    private void exportOrfsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportOrfsMenuItemActionPerformed
        if (dnaSaved == false) {
            errorPopup("DNA sequence has to be saved before ORFs can be stored!");
        } else {
            try {
                opslag.saveORFs(gevondenORFs);
            } catch (ArrayIndexOutOfBoundsException ex) {
                errorPopup("Empty list found!");
            } catch (SQLException ex) {
                errorPopup("SQL Error");
            } catch (OngelijkAantalKolommenException ex) {
                errorPopup("Amount of values to be inserted does not match amount of columns in SQL table");
            }
        }

    }//GEN-LAST:event_exportOrfsMenuItemActionPerformed
    /**
     * Wordt aangeroepen als gebruiker op "Vind ORFs" klikt. Laat de ORFs
     * opzoeken en deze visualiseren op de textPanes die de aminozuursequenties
     * bevatten.
     *
     * @param evt gebruiker klikt knop.
     */
    private void vindORFsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vindORFsButtonActionPerformed
        ORFSearcher orfFinder = new ORFSearcher();

        try {
            orfFinder.vindORFs(fastaSequentie);
            gevondenORFs = orfFinder.getORFLijst();
            Visualisator visualisatie = new Visualisator(gevondenORFs);
            visualisatie.visualizeOnPanes(aaSequentieTextPaneUpper, aaSequentieTextPaneLower);

        } catch (CompoundNotFoundException ex) {
            errorPopup("Invalid DNA sequence");
        } catch (BadLocationException ex) {
            errorPopup("SQL Error");
        } catch (OngeldigeORFException ex) {
            errorPopup("Amount of values to be inserted does not match amount of columns in SQL table");
        }


    }//GEN-LAST:event_vindORFsButtonActionPerformed
    /**
     * Wordt aangeroepen als gebruiker Export to DB -> Full DNA Seq klikt. Laat
     * de gehele ingeladen FASTA sequentie (DNA sequentie met FASTA titel)
     * opslaan in de MySQL DB.
     *
     * @param evt gebruiker selecteert het item.
     */
    private void exportDnaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportDnaMenuItemActionPerformed
        try {
            opslag = new SpecifiekeDataOpslag();
            opslag.saveDNA(fastaSequentie);
            dnaSaved = true;

        } catch (SQLException ex) {
            errorPopup("SQL Error");
        } catch (ClassNotFoundException ex) {
            errorPopup("SQL DRIVER Error");
        } catch (NullPointerException ex) {
            errorPopup("No DNA sequence found");
        } catch (OngelijkAantalKolommenException ex) {
            errorPopup("Amount of values to be inserted does not match amount of columns in SQL table");
        }
    }//GEN-LAST:event_exportDnaMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);

            }
        });
    }

    /**
     * Dient enkel om de pop-up window voor exceptions aan te maken, afhankelijk
     * van de exception zal de werkelijk getoonde tekst verschillen
     *
     * @param errortekst de tekst (meegegeven bij de exception) dat getoond
     * wordt in de pop-up window
     */
    public void errorPopup(String errortekst) {
        JOptionPane.showMessageDialog(this, errortekst, "FOUTJE", JOptionPane.WARNING_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextPane aaSequentieTextPaneLower;
    private javax.swing.JTextPane aaSequentieTextPaneUpper;
    private javax.swing.JMenuItem browseMenuItem;
    private javax.swing.JTextPane dnaSequentieTextPane;
    private javax.swing.JScrollPane dummyLowerScrollPane;
    private javax.swing.JPanel dummyPanel1;
    private javax.swing.JPanel dummyUpperPanel;
    private javax.swing.JScrollPane dummyUpperScrollPane;
    private javax.swing.JMenuItem exportBlastMenuItem;
    private javax.swing.JMenuItem exportDnaMenuItem;
    private javax.swing.JMenuItem exportOrfsMenuItem;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JButton openButton;
    private javax.swing.JTextField padTextField;
    private javax.swing.JMenuItem saveBlastMenuItem;
    private javax.swing.JMenuItem saveDnaMenuItem;
    private javax.swing.JMenuItem saveOrfsMenuItem;
    private javax.swing.JScrollPane seqScrollPane;
    private javax.swing.JButton vindORFsButton;
    // End of variables declaration//GEN-END:variables
}
